### ISSUE TITLE
500 error when submitting content with a schedule

### ISSUE THREAD

**Issue by gbprz** [concerto-addons/concerto_content_scheduling#19]
I received an email from a user trying to use this plugin with v2.2 and he reported the following:

```
W, [2014-12-19T10:04:53.582370 #3025]  WARN -- : ConcertoPlugin: use_plugin_ability: No Ability found for ConcertoContentScheduling
I, [2014-12-19T10:04:53.618362 #3025]  INFO -- :   Rendered /home/concerto/concerto_content_scheduling/app/views/concerto_content_scheduling/content/_details.html.erb (34.9ms)
I, [2014-12-19T10:04:53.618499 #3025]  INFO -- :   Rendered contents/_show_details.html.erb (41.6ms)
I, [2014-12-19T10:04:53.618689 #3025]  INFO -- :   Rendered contents/show.html.erb within layouts/application (56.6ms)
I, [2014-12-19T10:04:53.618888 #3025]  INFO -- : Completed 500 Internal Server Error in 98ms
E, [2014-12-19T10:04:54.285133 #3025] ERROR -- : ** [Airbrake] Failure: Net::HTTPBadGateway
F, [2014-12-19T10:04:54.291128 #3025] FATAL -- :
ActionView::Template::Error (757: unexpected token at 'custom'):
     5:   <% if @content.respond_to?(:has_schedule?) and @content.has_schedule? %>
     6:     <li><%=t('.from') %> <%= l Time.parse(@content.schedule_info['start_time']), :format => :twelve_hour_time %></li>
     7:     <li><%=t('.until') %> <%= l Time.parse(@content.schedule_info['end_time']),:format => :twelve_hour_time %></li>
     8:     <li><%= @content.schedule_in_words %></li>
     9:   <% else %>
    10:     <li><%=t('.available')%></li>
    11:   <% end %>
  app/models/concerto_plugin.rb:110:in `block (2 levels) in render_view_hook'
  app/models/concerto_plugin.rb:106:in `each'
  app/models/concerto_plugin.rb:106:in `block in render_view_hook'
  app/models/concerto_plugin.rb:104:in `render_view_hook'
  app/views/contents/_show_details.html.erb:22:in `_app_views_contents__show_details_html_erb___1732261134179886557_51316520'
  app/views/contents/show.html.erb:41:in `_app_views_contents_show_html_erb__44682804800949407_50469220'
  app/controllers/contents_controller.rb:36:in `show'
  app/controllers/application_controller.rb:112:in `set_time_zone'


I, [2014-12-19T10:04:54.292544 #3025]  INFO -- : Processing by ErrorsController#render_error as HTML
I, [2014-12-19T10:04:54.292934 #3025]  INFO -- :   Parameters: {"id"=>"2"}
I, [2014-12-19T10:04:54.423243 #3025]  INFO -- :   Rendered errors/error_generic.html.erb within layouts/no-topmenu (2.2ms)
I, [2014-12-19T10:04:54.425595 #3025]  INFO -- :   Rendered elements/_head.html.erb (0.1ms)
I, [2014-12-19T10:04:54.426415 #3025]  INFO -- : Completed 500 Internal Server Error in 133ms (Views: 129.9ms | ActiveRecord: 0.3ms)
```

**Comment by mholtrlc** [comment]
I am having this same issue, I ran the command mentioned above.

<code>

I, [2015-03-09T14:55:51.919250 #25727]  INFO -- : Started GET "/screens/1" for 10.20.20.140 at 2015-03-09 14:55:51 -0400
I, [2015-03-09T14:55:51.921317 #25727]  INFO -- : Processing by ScreensController#show as HTML
I, [2015-03-09T14:55:51.921385 #25727]  INFO -- :   Parameters: {"id"=>"1"}
I, [2015-03-09T14:55:51.949962 #25727]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/concerto_hardware-0.2/app/views/concerto_hardware/screens/_screen_link.html.erb (0.4ms)
W, [2015-03-09T14:55:51.951242 #25727]  WARN -- : ConcertoPlugin: use_plugin_ability: No Ability found for ConcertoTemplateScheduling
I, [2015-03-09T14:55:51.962151 #25727]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/concerto_template_scheduling-0.0.5/app/views/concerto_template_scheduling/screens/_screen_link.html.erb (10.7ms)
I, [2015-03-09T14:55:51.962294 #25727]  INFO -- :   Rendered screens/show.html.erb within layouts/application (20.8ms)
I, [2015-03-09T14:55:51.962511 #25727]  INFO -- : Completed 500 Internal Server Error in 41ms
E, [2015-03-09T14:55:52.254225 #25727] ERROR -- : ** [Airbrake] Failure: Net::HTTPBadGateway
F, [2015-03-09T14:55:52.257374 #25727] FATAL -- : 
ActionView::Template::Error (757: unexpected token at 'custom'):
    34:                   <p>
    35:                     <%= link_to(template_scheduling.schedule_path(schedule)) do %>
    36:                       <%= l(schedule.start_time.to_date, :format => :short) %> - <%= l(schedule.end_time.to_date, :format => :short) %>
    37:                     <% end %> <b><%= schedule.is_effective? ? t(:active) : '' %></b>
    38:                   </p>
    39:                   <p><b><%= ConcertoTemplateScheduling::Schedule::DISPLAY_WHEN.key(schedule.config['display_when'].to_i) %></b></p>
    40: 
  app/models/concerto_plugin.rb:110:in `block (2 levels) in render_view_hook'
  app/models/concerto_plugin.rb:106:in `each'
  app/models/concerto_plugin.rb:106:in `block in render_view_hook'
  app/models/concerto_plugin.rb:104:in `render_view_hook'
  app/views/screens/show.html.erb:1:in `_app_views_screens_show_html_erb__1238938330362039728_50515320'
  app/controllers/screens_controller.rb:24:in `show'
  app/controllers/application_controller.rb:112:in `set_time_zone'


I, [2015-03-09T14:55:52.257953 #25727]  INFO -- : Processing by ErrorsController#render_error as HTML
I, [2015-03-09T14:55:52.258016 #25727]  INFO -- :   Parameters: {"id"=>"1"}
I, [2015-03-09T14:55:52.261507 #25727]  INFO -- :   Rendered errors/error_generic.html.erb within layouts/no-topmenu (0.6ms)
I, [2015-03-09T14:55:52.262363 #25727]  INFO -- :   Rendered elements/_head.html.erb (0.1ms)
I, [2015-03-09T14:55:52.262772 #25727]  INFO -- : Completed 500 Internal Server Error in 5ms (Views: 2.2ms | ActiveRecord: 0.3ms)</code>

**Comment by mholtrlc** [comment]
My bad just realized this is the content scheduling plug i'm having the issue with the template scheduling, will repost
