### ISSUE TITLE
Plugin not working in new 2.3.1 VM

### ISSUE THREAD

**Issue by robp2175** [concerto-addons/concerto_content_scheduling#24]
I am using the new virtual machine download of 2.3.1. I Installed this plugin and it is not working. When I click frequency to Set schedule, nothing pops up. I should see the image below, as I used to, but I get nothing. Again, I am using the VM made by you guys without any modifications. 

![screen shot 11-25-15 at 08 57 am](https://cloud.githubusercontent.com/assets/8832179/11398979/5012f878-9352-11e5-843f-b6731e3384b6.PNG)

**Comment by mfrederickson** [comment]
Can you look in the developer console in chrome and see if there are any js errors or 404s for included js files?

**Comment by robp2175** [comment]
Files application.js and application.css are not being being found.

Sent from my iPhone

On Nov 26, 2015, at 6:21 PM, Marvin Frederickson <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you look in the developer console in chrome and see if there are any js errors or 404s for included js files?

> On Nov 25, 2015, at 4:56 AM, robp2175 <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> I am using the new virtual machine download of 2.3.1. I Installed this plugin and it is not working. When I click frequency to Set schedule, nothing pops up. I should see the image below, as I used to, but I get nothing. Again, I am using the VM made by you guys without any modifications.
>
>
>
> -
> Reply to this email directly or view it on GitHub.
>

-

**Comment by robp2175** [comment]
FYI. I did try rake assets:precompile RAILS_ENV=production, but this did nothing to alleviate the problem.

**Comment by mfrederickson** [comment]
I need to download the 2.3.1... it will be a couple hours...

**Comment by mfrederickson** [comment]
Rob, I was able to solve the problem.  What I had to do was:
```
cd /usr/share/concerto
sudo bash
RAILS_ENV=production bundle exec rake assets:precompile
chown -R www-data:www-data public
service apache2 restart
```
Then I refreshed the Add content page in the brower and everything worked fine.  If that works for you, close this ticket, otherwise we'll keep working on it.

**Comment by robp2175** [comment]
Perfect Marvin, worked like a charm. Thank you for looking into this. You are your colleagues efforts are greatly appreciated.
