### ISSUE TITLE
Content Scheduling Not working for RSS Feeds

### ISSUE THREAD

**Issue by robp2175** [concerto-addons/concerto_content_scheduling#25]
I have a feed that parses NFL Scores and I only want to show this feed on Sunday and Monday. This is an example of the feed. http://cfbangor.com/nfl.php. I style the feed using the code below. I setup the content scheduling to only show this feed on Sunday and Monday. However, It shows the feed everyday. The scheduler seems to work with other content, but not RSS Feeds. 

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
 <xsl:output method="html"/>
<xsl:template match="/rss">
    <xsl:apply-templates select="channel/item"/>
  </xsl:template>
  <xsl:template match="item">
        <content-item>
      <xsl:for-each select=". ">

<div style="margin-top:10px;font-size:3vw; background-image: url(http://concerto.domain.edu:81/sports/nfl2.png); background-repeat: no-repeat; background-size: 45px; background-position: 5px;"><span style="margin-left: 100px;"><xsl:value-of select="title"/></span>
</div>



      </xsl:for-each>
      </content-item>
</xsl:template>
</xsl:stylesheet>
```

**Comment by mfrederickson** [comment]
Interesting... we should look to make sure the schedule applies to dynamic content...

**Comment by mfrederickson** [comment]
@augustf This is fixed, but requires the PR for the dynamic-content-hook in concerto (forthcoming).
